#!/usr/bin/env bash

# environment variables
if [[ -z $STOW_FOLDERS ]]; then
	STOW_FOLDERS=("nvim" "vim" "tmux" "karabiner" "ideavim" "zsh" "git" "ssh" "gpg" "aerospace" "claude")
	# STOW_FOLDERS=("vim" "tmux" "karabiner" "ideavim" "zsh" "git" "ssh" "gpg")
fi

if [[ -z $DOTFILES ]]; then
	DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS
DOTFILES=$DOTFILES

# Firefox profile variables
FIREFOX_PROFILE_PATH=$(grep "Default=" ~/Library/Application\ Support/Firefox/installs.ini | cut -d'=' -f2 | tr -d '\n\r ')
FIREFOX_FULL_PATH="$HOME/Library/Application Support/Firefox/$FIREFOX_PROFILE_PATH"
